### ISSUE TITLE
requirements.txt file not found in project(?)

### ISSUE THREAD

**Issue by jpfr12** [toaster-code/youtube_audio_extractor#1]
On the 2nd step of the installation of the App, we need to have a file named "requirements.txt".
Where is it?

**Comment by toaster-code** [comment]
Hi jpfr12, 
I am sorry, I forgot to mention that I am using poetry. Dependencies are in poetry.lock
You may use this command to extract the requirements:
`poetry export --without-hashes --format=requirements.txt > requirements.txt`

Here is what I am using at this date after extracting dependencies from lock file:
```
appdirs==1.4.4
certifi==2022.12.7
charset-normalizer==3.0.1
colorama==0.4.6
ffmpeg-downloader==0.2.0
idna==3.4
packaging==23.0
pytube==12.1.2
requests==2.28.2
tqdm==4.64.1
urllib3==1.26.14

```

**Comment by toaster-code** [comment]
> On the 2nd step of the installation of the App, we need to have a file named "requirements.txt". Where is it?

Hi jpfr12,
I am sorry, I forgot to mention that I am using poetry. Dependencies are in poetry.lock
If you have poetry installed, use this command to extract the requirements:
`poetry export --without-hashes --format=requirements.txt > requirements.txt`

Here is what I am using at this date after extracting dependencies from the lock file:

```
python==^3.9
youtube_dl==^2021.12.17
ffmpeg-downloader==^0.2.0
pytube==^12.1.2

```

**Comment by jpfr12** [comment]
Thank you for replying :)
